# 1. Comparando Julia Lang com Python

In [4]:
# Cria uma matriz 2x3 de zeros
matriz_zeros = zeros(2, 3)

# Exibe a matriz
println("Matriz 2x3 de zeros:")
println(matriz_zeros)

Matriz 2x3 de zeros:
[0.0 0.0 0.0; 0.0 0.0 0.0]


In [7]:
size(matriz_zeros)

(2, 3)

In [41]:
s = ones(String, 1, 3)
s

1×3 Matrix{String}:
 ""  ""  ""

- Built-in arrays (List)

In [13]:
a = [1 2 3; 4 5 6; 7 8 9]
a

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

- Aqui também enderessamos por colchetes

In [16]:
# Criando matriz contendo zeros em todas linhas
z = zeros(Float64, 2, 3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [17]:
z[1, 2] = 3.1415

3.1415

In [18]:
z

2×3 Matrix{Float64}:
 0.0  3.1415  0.0
 0.0  0.0     0.0

- Produto entre dois vetores:
$\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^n a_i b_i$

In [19]:
# Lib para trabalhar com Álgebra Linear
using LinearAlgebra

In [20]:
a = [1, 2, 3]
b = [3, 4, 5]

3-element Vector{Int64}:
 3
 4
 5

In [22]:
println("Produto Escalar: ", dot(a, b))

Produto Escalar: 26


### Trabalhando com $\pi$

In [33]:
vetor_coluna = fill(π, 8, 8)

8×8 Matrix{Irrational{:π}}:
 π  π  π  π  π  π  π  π
 π  π  π  π  π  π  π  π
 π  π  π  π  π  π  π  π
 π  π  π  π  π  π  π  π
 π  π  π  π  π  π  π  π
 π  π  π  π  π  π  π  π
 π  π  π  π  π  π  π  π
 π  π  π  π  π  π  π  π

In [35]:
print("Vetor coluna com valores pi: ", vetor_coluna)

Vetor coluna com valores pi: [π π π π π π π π; π π π π π π π π; π π π π π π π π; π π π π π π π π; π π π π π π π π; π π π π π π π π; π π π π π π π π; π π π π π π π π]