## 1. Numpy 

#### Packages

In [31]:
import numpy as np
import random

- Criando Arrays

In [6]:
b = np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [17]:
c = np.full((2,2), 3.1415)
print(c)
print(c.dtype)

[[3.1415 3.1415]
 [3.1415 3.1415]]
float64


In [20]:
# Criando matrizes identidade
d = np.eye(4)
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
# Criando matrizes diagonais
a = np.diag(np.arange(3))
print(f" Criando uma matriz: \n {a} \n \n")
print(f" Tipo de dado: {type(a)}")

 Criando uma matriz: 
 [[0 0 0]
 [0 1 0]
 [0 0 2]] 
 

 Tipo de dado: <class 'numpy.ndarray'>


In [34]:
import numpy as np  # Importa o numpy

rng = np.random.default_rng()  # Usa o gerador de números aleatórios do numpy
g = rng.integers(low=5, high=12, size=(2, 5))  # Gera números inteiros
print(g)

[[ 8  9  8 11 11]
 [ 7 10  5 10  6]]


In [42]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Transforma o array em uma matriz 3x3
matriz = a.reshape(3, 3)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
b = matriz[:2, 1:3]
b

array([[2, 3],
       [5, 6]])

In [53]:
# Geração de um array booleano
array_booleano = np.array([True, False, False, True])
matriz_boolean = array_booleano.reshape(2, 2)


print(f"Criando Array boolean: \n {array_booleano}\n \
      Criando uma matriz boolean {matriz}")

Criando Array boolean: 
 [ True False False  True]
       Criando uma matriz boolean [[1 2 3]
 [4 5 6]
 [7 8 9]]


- Multiplicando vetores em Python: 

In [66]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
produto_escalar = np.dot(a, b)

print("Produto escalar:", produto_escalar)

Produto escalar: 32


- Geradores de números aleatórios

In [73]:
def escolha():
    # Definindo os números e suas probabilidades
    numeros = [1, 2, 3, 4]
    probabilidades = [0.0, 0.4, 0.3, 0.2]  # Probabilidades para cada número

    # Sorteando um número com base nas probabilidades
    numero_sorteado = random.choices(numeros, weights=probabilidades, k=1)[0]

    return numero_sorteado

# Testando a função
print("Número sorteado:", escolha())

Número sorteado: 3
